### ISSUE TITLE
Dropping `python-` prefix

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/python-drmaa-feedstock#3]
As this is a `defaults` package and we have backed out `python-` prefixes from everything else in `defaults`, we should probably do the same with this.

The long term solution will probably be the more sophisticated [namespacing](https://gist.github.com/mcg1969/da5aec380d2ed083b79ddcf151ca16f1) strategy. This is only outlined as a gist ATM. Though this will get baked into `conda` and `conda-build`.

cc @pelson

**Comment by dan-blanchard** [comment]
For consistency it makes a bit of sense, but that namespacing can't get here soon enough.

**Comment by pelson** [comment]
Agreed. It hurts to drop the prefix, but at the moment our hands are tied due to the fact there would be two packages of different name (`python-drmaa` and `drmaa`) each writing to the same directory in site-packages - we can't guarantee that one wont overwrite the other to an unpredictable outcome.

**Comment by jakirkham** [comment]
Should be fixed by PR ( https://github.com/conda-forge/python-drmaa-feedstock/pull/6 ).

**Comment by jakirkham** [comment]
Have resolved the remaining actionables for this.

**Comment by mivade** [comment]
I had an issue today by mistakenly installing `python-drmaa` (which is outdated) instead of `drmaa`. Is there any reason to keep the old package around? At the very least maybe update its description to make it more obvious that everyone should be using `drmaa`.

**Comment by jakirkham** [comment]
The `python-drmaa` packages have now been labeled as `broken` and pulled from `main`. Hopefully that helps.

**Comment by sebastian-luna-valero** [comment]
The reason to keep the old package is to maintain reproducibility of packages created when only `python-drmaa` was around. That's the case for us. Not sure how many people would be affected as well.
